# Topic 02: Introducing the pandas DataFrame

This notebook combines the course-provided lesson material and its exercise section. The answers follow the original prompts and use the pandas methods demonstrated in the lessons. Data files for this topic are stored in the adjacent `Datasets` folder. The requested conda environment is `CISC7204_BonusAssgn_ENV` (Python 3.13).

In [1]:
from pathlib import Path

DATA_DIR = Path("Datasets")

---

## Course lesson: 02_PandasDataFrames_01.ipynb

# Intro to Pandas
by Ryan Orsinger

## Module 2: Introducing DataFrames

### Pandas DataFrames Basics - Part 1
- How to make pandas DataFrames from other Python collections
- Learning about your dataframe's properties and information
- Selecting a single column
- Adding new columns to a DataFrame
- Renaming columns
- Descriptive stats on the columns

In [2]:
import pandas as pd

In [3]:
# Creating a dataframe from a list of dictionaries
basket = [
    {"item": "mango", "quantity": 4, "price": 2.99},
    {"item": "bread", "quantity": 2, "price": 3.25},
    {"item": "juice", "quantity": 1, "price": 5.90},
    {"item": "orange", "quantity": 3, "price": 2.99},
    {"item": "lime", "quantity": 3, "price": 0.3},
]
basket

[{'item': 'mango', 'quantity': 4, 'price': 2.99},
 {'item': 'bread', 'quantity': 2, 'price': 3.25},
 {'item': 'juice', 'quantity': 1, 'price': 5.9},
 {'item': 'orange', 'quantity': 3, 'price': 2.99},
 {'item': 'lime', 'quantity': 3, 'price': 0.3}]

In [4]:
# With dataframes, our columns are our variables or features
# Each row represents a unique observation (usually)
df = pd.DataFrame(basket)
df

     item  quantity  price
0   mango         4   2.99
1   bread         2   3.25
2   juice         1   5.90
3  orange         3   2.99
4    lime         3   0.30

In [5]:
# Creating a dataframe from a dictionary of lists
basket = {
    "item": ["mango", "bread", "juice", "orange", "lime"],
    "quantity": [4, 2, 1, 3, 3],
    "price": [2.99, 3.25, 5.90, 2.99, 0.30]
}
basket

{'item': ['mango', 'bread', 'juice', 'orange', 'lime'],
 'quantity': [4, 2, 1, 3, 3],
 'price': [2.99, 3.25, 5.9, 2.99, 0.3]}

In [6]:
pd.DataFrame(basket)

     item  quantity  price
0   mango         4   2.99
1   bread         2   3.25
2   juice         1   5.90
3  orange         3   2.99
4    lime         3   0.30

In [7]:
# Creating a dataframe from a list of lists
example = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

column_names = ["variable_a", "variable_b", "variable_c"]
row_names = ["observation_1", "observation_2", "observation_3"]

pd.DataFrame(example, columns=column_names, index=row_names)

               variable_a  variable_b  variable_c
observation_1           1           2           3
observation_2           4           5           6
observation_3           7           8           9

In [8]:
# Creating an empty dataframe
df = pd.DataFrame()

# Adding columns to a dataframe
# Any list-like data type can become a column
df["item"] = pd.Series(["Mango", "Bread", "Juice", "Orange", "Lime"])
df["quantity"] = [2, 2, 1, 3, 3]
df["price"] = (2.99, 3.25, 5.90, 2.99, 0.30)
df

     item  quantity  price
0   Mango         2   2.99
1   Bread         2   3.25
2   Juice         1   5.90
3  Orange         3   2.99
4    Lime         3   0.30

In [9]:
# .shape returns rows, columns
df.shape

(5, 3)

In [10]:
# Returns the rows
df.shape[0]

5

In [11]:
# Returns the number of columns
df.shape[1]

3

In [12]:
# len returns number of rows
len(df)

5

In [13]:
# size returns rows * columns
df.size

15

In [14]:
# Adding new columns to the dataframe
df["subtotal"] = df["quantity"] * df["price"]
df

     item  quantity  price  subtotal
0   Mango         2   2.99      5.98
1   Bread         2   3.25      6.50
2   Juice         1   5.90      5.90
3  Orange         3   2.99      8.97
4    Lime         3   0.30      0.90

In [15]:
# set_index can overwrite the default index
df.set_index("item", inplace=True)
df

        quantity  price  subtotal
item
Mango          2   2.99      5.98
Bread          2   3.25      6.50
Juice          1   5.90      5.90
Orange         3   2.99      8.97
Lime           3   0.30      0.90

In [16]:
# Accessing the index values
df.index

Index(['Mango', 'Bread', 'Juice', 'Orange', 'Lime'], dtype='str', name='item')

In [17]:
# We can also overwrite the index with a Series of equal length
df.index = df.index.str.lower()
df

        quantity  price  subtotal
item
mango          2   2.99      5.98
bread          2   3.25      6.50
juice          1   5.90      5.90
orange         3   2.99      8.97
lime           3   0.30      0.90

In [18]:
# Accessing all the columns
df.columns

Index(['quantity', 'price', 'subtotal'], dtype='str')

In [19]:
# Another example of creating a new column
df["tax"] = 0.07
df

        quantity  price  subtotal   tax
item
mango          2   2.99      5.98  0.07
bread          2   3.25      6.50  0.07
juice          1   5.90      5.90  0.07
orange         3   2.99      8.97  0.07
lime           3   0.30      0.90  0.07

In [20]:
# The "total cost" column does not exist, but this bracket syntax creates it.
df["total cost"] = df["subtotal"] + (df["subtotal"] * df["tax"])
df

        quantity  price  subtotal   tax  total cost
item
mango          2   2.99      5.98  0.07      6.3986
bread          2   3.25      6.50  0.07      6.9550
juice          1   5.90      5.90  0.07      6.3130
orange         3   2.99      8.97  0.07      9.5979
lime           3   0.30      0.90  0.07      0.9630

In [21]:
# Dot syntax also allows for calling an existing column
# Using .column syntax only works if the column exists already, has no spaces, and is not a dataframe method already
df.price

item
mango     2.99
bread     3.25
juice     5.90
orange    2.99
lime      0.30
Name: price, dtype: float64

In [22]:
# .dtypes outputs the datatypes of all columns in the dataframe
df.dtypes

quantity        int64
price         float64
subtotal      float64
tax           float64
total cost    float64
dtype: object

In [23]:
# .info returns datatype and non-null count
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, mango to lime
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   quantity    5 non-null      int64
 1   price       5 non-null      float64
 2   subtotal    5 non-null      float64
 3   tax         5 non-null      float64
 4   total cost  5 non-null      float64
dtypes: float64(4), int64(1)
memory usage: 412.0+ bytes

In [24]:
df.price.describe()

count    5.000000
mean     3.086000
std      1.982783
min      0.300000
25%      2.990000
50%      2.990000
75%      3.250000
max      5.900000
Name: price, dtype: float64

In [25]:
# Show descriptive stats for numeric columns
df.describe()

       quantity     price  subtotal   tax  total cost
count   5.00000  5.000000  5.000000  5.00    5.000000
mean    2.20000  3.086000  5.650000  0.07    6.045500
std     0.83666  1.982783  2.935933  0.00    3.141448
min     1.00000  0.300000  0.900000  0.07    0.963000
25%     2.00000  2.990000  5.900000  0.07    6.313000
50%     2.00000  2.990000  5.980000  0.07    6.398600
75%     3.00000  3.250000  6.500000  0.07    6.955000
max     3.00000  5.900000  8.970000  0.07    9.597900

In [26]:
# A column in a dataframe is a series
type(df.quantity)

pandas.Series

In [27]:
# .value_counts returns a series
df.quantity.value_counts()

quantity
2    2
3    2
1    1
Name: count, dtype: int64

In [28]:
# Aggregate functions can run on all the numeric values in the dataframe
df.mean()

quantity      2.2000
price         3.0860
subtotal      5.6500
tax           0.0700
total cost    6.0455
dtype: float64

In [29]:
# Obtain the median of all numeric columns
df.median()

quantity      2.0000
price         2.9900
subtotal      5.9800
tax           0.0700
total cost    6.3986
dtype: float64

In [30]:
# Standard deviation of all the numeric columns
df.std()

quantity      0.836660
price         1.982783
subtotal      2.935933
tax           0.000000
total cost    3.141448
dtype: float64

In [31]:
# The square bracket syntax can be used to access column names with spaces
# Same with column names that are methods on the dataframe object
# Recommend avoiding column names with spaces, removing spaces when you encounter them
# Recommend avoiding naming columns after dataframe method
df["shape"] = ["round", "loaf", "jug", "round", "round"]
df

        quantity  price  subtotal   tax  total cost  shape
item
mango          2   2.99      5.98  0.07      6.3986  round
bread          2   3.25      6.50  0.07      6.9550   loaf
juice          1   5.90      5.90  0.07      6.3130    jug
orange         3   2.99      8.97  0.07      9.5979  round
lime           3   0.30      0.90  0.07      0.9630  round

In [32]:
# Remember that the .shape attribute shows # rows, #columns
df.shape

(5, 6)

In [33]:
# The bracket quote syntax returns the column
df["shape"]

item
mango     round
bread      loaf
juice       jug
orange    round
lime      round
Name: shape, dtype: str

In [34]:
# Naming columns the same as built-in dataframe methods and spaces in column names are not helpful
# .rename allows for renaming columns in a dataframe using a dictionary
df.rename(columns={"shape": "item_shape", "total cost": "total"}, inplace=True)
df

        quantity  price  subtotal   tax   total item_shape
item
mango          2   2.99      5.98  0.07  6.3986      round
bread          2   3.25      6.50  0.07  6.9550       loaf
juice          1   5.90      5.90  0.07  6.3130        jug
orange         3   2.99      8.97  0.07  9.5979      round
lime           3   0.30      0.90  0.07  0.9630      round

## Exercises
- Assign dataframe named `items` out of the following list of dictionaries.
```
items = [
    {"item name": "USB cable", "price": "$10.99", "type": "USB C to USB C"},
    {"item name": "USB cable", "price": "$10.99", "type": "USB A to USB C"},
    {"item name": "Batteries", "price": "$9.99", "type": "AA"},
    {"item name": "Batteries", "price": "$8.99", "type": "AAA"},
    {"item name": "Mouse", "price": "$12.99", "type": "Wireless USB"},
]
```
- Rename the `item name` column to `item_name`
- Add a column named `units_sold` to this dataframe and assign the values `[41, 113, 54, 35, 22]`
- Use what you learned from working with strings to convert the price column into a float (hint: remove non-numeric characters before attempting to convert the data type to a float)
- Create a new column named `total_revenue` that holds the `price` column times the `units_sold` column
- Round the `total_revenue` column values to the nearest cent. (hint: search or consult the pandas documentation

In [35]:
# Assign dataframe named `items` out of the following list of dictionaries.


items = [
    {"item name": "USB cable", "price": "$10.99", "type": "USB C to USB C"},
    {"item name": "USB cable", "price": "$10.99", "type": "USB A to USB C"},
    {"item name": "Batteries", "price": "$9.99", "type": "AA"},
    {"item name": "Batteries", "price": "$8.99", "type": "AAA"},
    {"item name": "Mouse", "price": "$12.99", "type": "Wireless USB"},
]
items = pd.DataFrame(items)
items

   item name   price            type
0  USB cable  $10.99  USB C to USB C
1  USB cable  $10.99  USB A to USB C
2  Batteries   $9.99              AA
3  Batteries   $8.99             AAA
4      Mouse  $12.99    Wireless USB

In [36]:
# Rename the item name column to item_name


items = items.rename(columns={"item name": "item_name"})
items

   item_name   price            type
0  USB cable  $10.99  USB C to USB C
1  USB cable  $10.99  USB A to USB C
2  Batteries   $9.99              AA
3  Batteries   $8.99             AAA
4      Mouse  $12.99    Wireless USB

In [37]:
# Add a column named units_sold to this dataframe and assign the values [41, 113, 54, 35, 22]


items["units_sold"] = [41, 113, 54, 35, 22]
items

   item_name   price            type  units_sold
0  USB cable  $10.99  USB C to USB C          41
1  USB cable  $10.99  USB A to USB C         113
2  Batteries   $9.99              AA          54
3  Batteries   $8.99             AAA          35
4      Mouse  $12.99    Wireless USB          22

In [38]:
# Convert the price column into a float data type


items["price"] = items["price"].str.replace("$", "", regex=False)
items["price"] = items["price"].astype(float)
items

   item_name  price            type  units_sold
0  USB cable  10.99  USB C to USB C          41
1  USB cable  10.99  USB A to USB C         113
2  Batteries   9.99              AA          54
3  Batteries   8.99             AAA          35
4      Mouse  12.99    Wireless USB          22

In [39]:
# Create a new column named "total_revenue" that holds the `price` column times the `units_sold` column


items["total_revenue"] = items["price"] * items["units_sold"]
items

   item_name  price            type  units_sold  total_revenue
0  USB cable  10.99  USB C to USB C          41         450.59
1  USB cable  10.99  USB A to USB C         113        1241.87
2  Batteries   9.99              AA          54         539.46
3  Batteries   8.99             AAA          35         314.65
4      Mouse  12.99    Wireless USB          22         285.78

In [40]:
# Round the total_revenue column values to the nearest cent.


items["total_revenue"] = items["total_revenue"].round(2)
items

   item_name  price            type  units_sold  total_revenue
0  USB cable  10.99  USB C to USB C          41         450.59
1  USB cable  10.99  USB A to USB C         113        1241.87
2  Batteries   9.99              AA          54         539.46
3  Batteries   8.99             AAA          35         314.65
4      Mouse  12.99    Wireless USB          22         285.78

---

## Course lesson: 02_PandasDataFrames_02.ipynb

# Intro to Pandas
by Ryan Orsinger

## Module 2: Introducing DataFrames

### Pandas DataFrames Basics - Part 2
- Helpful Jupyter features
- Importing a CSV dataset
- Selecting multiple columns
- Counting True values in a Boolean series
- Filtering rows with Boolean masks
- Using AND and OR operators
- Why and when to use .copy
- Sorting a dataframe by one or more columns

In [41]:
import pandas as pd

In [42]:
# pd.read_csv reads a comma-separated value file and returns a dataframe
mpg = pd.read_csv(DATA_DIR / "mpg.csv")
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [43]:
# Showing the object.tab autocomplete option
# Type the variable that's already been evaluated in memory
# This works with imported modules, too
# Type .
# Then type the <Tab> character
mpg.count?

In [44]:
# Pulling up the docstring for a method
mpg.head?

In [45]:
# .tail looks at the last records of a pandas object (series or datafram)
mpg.tail(3)

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [46]:
# The square brackets on the dataframe can accept a list of column names 
columns_of_interest = ["displ", "cty", "hwy"]
mpg[columns_of_interest].head()

   displ  cty  hwy
0    1.8   18   29
1    1.8   21   29
2    2.0   20   31
3    2.0   21   30
4    2.8   16   26

In [47]:
# You'll also see the same result with double square brackets
mpg[["cty", "hwy"]].head()

   cty  hwy
0   18   29
1   21   29
2   20   31
3   21   30
4   16   26

In [48]:
# Our functions like .mean, .sum, .median, min/max evaluate an entire column, by default
# There's a default argument in .mean() that's axis=0 (which means column)
mpg[["cty", "hwy"]].mean(axis=0)

cty    16.858974
hwy    23.440171
dtype: float64

In [49]:
mpg[["cty", "hwy"]].head()

   cty  hwy
0   18   29
1   21   29
2   20   31
3   21   30
4   16   26

In [50]:
# axis=1 means execute the .mean on each row, row-wise execution
mpg[["cty", "hwy"]].mean(axis=1).head()

0    23.5
1    25.0
2    25.5
3    25.5
4    21.0
dtype: float64

In [51]:
# axis=1 calculates the row-wise average
mpg["average_mileage"] = mpg[["cty", "hwy"]].mean(axis=1)
mpg.head()

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class,average_mileage
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,23.5
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,25.0
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,25.5
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,25.5
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,21.0

In [52]:
# value_counts shows unique values and their distribution
mpg.cyl.value_counts()

cyl
4    81
6    79
8    70
5     4
Name: count, dtype: int64

In [53]:
# Using Boolean Series to answer questions
# How many audis in the dataset
# True works as a 1, False works as 0
(mpg.manufacturer == "audi").sum()

np.int64(18)

In [54]:
# What proportion of engines are 4 cylinders?
(mpg.cyl == 4).mean()

np.float64(0.34615384615384615)

In [55]:
# Using Boolean Series to filter a dataframe
mpg[mpg.cyl == 5]

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class,average_mileage
217,volkswagen,jetta,2.5,2008,5,auto(s6),f,21,29,r,compact,25.0
218,volkswagen,jetta,2.5,2008,5,manual(m5),f,21,29,r,compact,25.0
225,volkswagen,new beetle,2.5,2008,5,manual(m5),f,20,28,r,subcompact,24.0
226,volkswagen,new beetle,2.5,2008,5,auto(s6),f,20,29,r,subcompact,24.5

In [56]:
# You can mix and match the columns used to generate Booleans, the Boolean values don't care
mpg[(mpg.model == "maxima") | (mpg.cyl == 5)]

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class,average_mileage
147,nissan,maxima,3.0,1999,6,auto(l4),f,18,26,r,midsize,22.0
148,nissan,maxima,3.0,1999,6,manual(m5),f,19,25,r,midsize,22.0
149,nissan,maxima,3.5,2008,6,auto(av),f,19,25,p,midsize,22.0
217,volkswagen,jetta,2.5,2008,5,auto(s6),f,21,29,r,compact,25.0
218,volkswagen,jetta,2.5,2008,5,manual(m5),f,21,29,r,compact,25.0
225,volkswagen,new beetle,2.5,2008,5,manual(m5),f,20,28,r,subcompact,24.0
226,volkswagen,new beetle,2.5,2008,5,auto(s6),f,20,29,r,subcompact,24.5

In [57]:
# AND limits options. Both predicates must be true
mpg[(mpg["class"] == "midsize") & (mpg["displ"] < 2)]

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class,average_mileage
227,volkswagen,passat,1.8,1999,4,manual(m5),f,21,29,p,midsize,25.0
228,volkswagen,passat,1.8,1999,4,auto(l5),f,18,29,p,midsize,23.5

In [58]:
original_df = pd.DataFrame({"x": [1, 2, 3]})
original_df

   x
0  1
1  2
2  3

In [59]:
# Be careful assigning Python collections like this...
# This works the same way with lists, dictionaries, and many other collection objects
new_df = original_df

In [60]:
original_df["y"] = original_df.x * 100
original_df

   x    y
0  1  100
1  2  200
2  3  300

In [61]:
new_df

   x    y
0  1  100
1  2  200
2  3  300

In [62]:
# Use .copy to make a proper copy of a dataframe
new_df = original_df.copy()
new_df

   x    y
0  1  100
1  2  200
2  3  300

In [63]:
original_df["z"] = 5000
original_df

   x    y     z
0  1  100  5000
1  2  200  5000
2  3  300  5000

In [64]:
# The new df was created from a copy and avoids future mutation to the original dataframe
new_df

   x    y
0  1  100
1  2  200
2  3  300

In [65]:
# Sorting by a single column
mpg.sort_values(by=["average_mileage"], ascending=False, ignore_index=True).head()

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class,average_mileage
0,volkswagen,new beetle,1.9,1999,4,manual(m5),f,35,44,d,subcompact,39.5
1,volkswagen,jetta,1.9,1999,4,manual(m5),f,33,44,d,compact,38.5
2,volkswagen,new beetle,1.9,1999,4,auto(l4),f,29,41,d,subcompact,35.0
3,toyota,corolla,1.8,2008,4,manual(m5),f,28,37,r,compact,32.5
4,toyota,corolla,1.8,2008,4,auto(l4),f,26,35,r,compact,30.5

In [66]:
# Sorting by multiple columns
mpg.sort_values(by=["hwy", "cty"], ascending=False, ignore_index=True).head()

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class,average_mileage
0,volkswagen,new beetle,1.9,1999,4,manual(m5),f,35,44,d,subcompact,39.5
1,volkswagen,jetta,1.9,1999,4,manual(m5),f,33,44,d,compact,38.5
2,volkswagen,new beetle,1.9,1999,4,auto(l4),f,29,41,d,subcompact,35.0
3,toyota,corolla,1.8,2008,4,manual(m5),f,28,37,r,compact,32.5
4,honda,civic,1.8,2008,4,auto(l5),f,25,36,r,subcompact,30.5

In [67]:
# Updating the dataframe to store the sorted values
# Use inplace=True or reassign the dataframe variable (not both)
mpg.sort_values(by="displ", ascending=False, ignore_index=True, inplace=True)
mpg.head()

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class,average_mileage
0,chevrolet,corvette,7.0,2008,8,manual(m6),r,15,24,p,2seater,19.5
1,chevrolet,k1500 tahoe 4wd,6.5,1999,8,auto(l4),4,14,17,d,suv,15.5
2,chevrolet,corvette,6.2,2008,8,auto(s6),r,15,25,p,2seater,20.0
3,chevrolet,corvette,6.2,2008,8,manual(m6),r,16,26,p,2seater,21.0
4,jeep,grand cherokee 4wd,6.1,2008,8,auto(l5),4,11,14,p,suv,12.5

## Additional Resources
- [Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)
- [Pandas Comparison to Spreadsheets](https://pandas.pydata.org/docs/dev/getting_started/comparison/comparison_with_spreadsheets.html)
- [Pandas Comparison to SQL](https://pandas.pydata.org/docs/dev/getting_started/comparison/comparison_with_sql.html)

## Exercises
- Create a new column named `is_automatic` that holds a Boolean if that given vehicle is an automatic transmition or not. 
- Use the `is_automatic` column to sum up the number of automatic vehicles in this dataset.
- Write the pandas code to determine what percentage of the vehicles are subcompacts?
- Combined fuel economy is a weighted average of the city value by 55% and the highway value by 45%. Use arithmetic operators to add a new column named `fuel_economy` to the `mpg` dataframe.
- Use Boolean masking to find all of the vehicles with a `fuel_economy` above the median `fuel_economy`.

In [68]:
# Create a new column named `is_automatic` that holds a Boolean if that given vehicle is an automatic transmition or not. 


mpg["is_automatic"] = mpg["trans"].str.startswith("auto")
mpg[["manufacturer", "model", "trans", "is_automatic"]].head()

  manufacturer               model       trans  is_automatic
0    chevrolet            corvette  manual(m6)         False
1    chevrolet     k1500 tahoe 4wd    auto(l4)          True
2    chevrolet            corvette    auto(s6)          True
3    chevrolet            corvette  manual(m6)         False
4         jeep  grand cherokee 4wd    auto(l5)          True

In [69]:
# Use the `is_automatic` column to sum up the number of automatic vehicles in this dataset.


mpg["is_automatic"].sum()

np.int64(157)

In [70]:
# Write the pandas code to determine what percentage of the vehicles are subcompacts?


subcompact_count = (mpg["class"] == "subcompact").sum()
subcompact_percentage = subcompact_count / len(mpg) * 100
subcompact_percentage

np.float64(14.957264957264957)

In [71]:
# Create a `fuel_economy` column. Fuel economy is a weighted average of the city value by 55% and the highway value by 45%


mpg["fuel_economy"] = mpg["cty"] * 0.55 + mpg["hwy"] * 0.45
mpg[["cty", "hwy", "fuel_economy"]].head()

   cty  hwy  fuel_economy
0   15   24         19.05
1   14   17         15.35
2   15   25         19.50
3   16   26         20.50
4   11   14         12.35

In [72]:
# Use Boolean masking to find all of the vehicles with a `fuel_economy` above the median `fuel_economy`.


median_fuel_economy = mpg["fuel_economy"].median()
mpg[mpg["fuel_economy"] > median_fuel_economy]

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class,average_mileage,is_automatic,fuel_economy
3,chevrolet,corvette,6.2,2008,8,manual(m6),r,16,26,p,2seater,21.0,False,20.50
9,chevrolet,corvette,5.7,1999,8,manual(m6),r,16,26,p,2seater,21.0,False,20.50
71,ford,mustang,4.0,2008,6,manual(m5),r,17,26,r,subcompact,21.5,False,21.05
89,pontiac,grand prix,3.8,2008,6,auto(l4),f,18,28,r,midsize,23.0,True,22.50
91,ford,mustang,3.8,1999,6,manual(m5),r,18,26,r,subcompact,22.0,False,21.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,honda,civic,1.6,1999,4,manual(m5),f,23,29,p,subcompact,26.0,False,25.70
230,honda,civic,1.6,1999,4,manual(m5),f,28,33,r,subcompact,30.5,False,30.25
231,honda,civic,1.6,1999,4,auto(l4),f,24,32,r,subcompact,28.0,True,27.60
232,honda,civic,1.6,1999,4,auto(l4),f,24,32,r,subcompact,28.0,True,27.60
233,honda,civic,1.6,1999,4,manual(m5),f,25,32,r,subcompact,28.5,False,28.15