# Topic 05: Combining DataFrames and working with files

This notebook combines the course-provided lesson material and its exercise section. The answers follow the original prompts and use the pandas methods demonstrated in the lessons. Data files for this topic are stored in the adjacent `Datasets` folder. The requested conda environment is `CISC7204_BonusAssgn_ENV` (Python 3.13).

In [1]:
from pathlib import Path

DATA_DIR = Path("Datasets")

---

## Course lesson: 05_Advanced_Dataframes_01.ipynb

# Intro to Pandas
by Ryan Orsinger

## Module 5: Combining Dataframes
- Using `.concat` to combine dataframes horizontally or vertically 
- Intro to joining dataframes together like database tables
- Understanding different types of joins
- Using `.merge` to join dataframes together based on column values in common

In [2]:
import pandas as pd

In [3]:
# String concatenation
"con" + "cat" + "e" + "nation"

'concatenation'

In [4]:
# List concatenation
["con", "cat"] + ["e", "nation"]

['con', 'cat', 'e', 'nation']

In [5]:
# Dataframe Concatenation 
fruits = pd.DataFrame({
    "name": ["mango", "guava", "orange"],
    "quantity": [2, 1, 3]
})

vegetables = pd.DataFrame({
    "name": ["Brussels sprouts", "spinach", "broccoli"],
    "quantity": [1, 7, 4]
})

In [6]:
# Default arguments preserve the original index for each dataframe
pd.concat([fruits, vegetables])

               name  quantity
0             mango         2
1             guava         1
2            orange         3
0  Brussels sprouts         1
1           spinach         7
2          broccoli         4

In [7]:
# Axis=0 is the default argument for concatenating dataframes
# This is vertical concatenation, since we're adding row-wise
pd.concat([fruits, vegetables], axis=0)

               name  quantity
0             mango         2
1             guava         1
2            orange         3
0  Brussels sprouts         1
1           spinach         7
2          broccoli         4

In [8]:
pd.concat([fruits, vegetables], ignore_index=True)

               name  quantity
0             mango         2
1             guava         1
2            orange         3
3  Brussels sprouts         1
4           spinach         7
5          broccoli         4

In [9]:
# Dataframe Concatenation 
fruits = pd.DataFrame({
    "name": ["mango", "guava", "orange"],
})

# Notice that this instance of vegetables lacks a quantity column
vegetables = pd.DataFrame({
    "name": ["Brussels sprouts", "spinach", "broccoli"],
    "quantity": [2, 3, 4]

})

# If a column is missing from a dataframe, its values will be missing, so the concatenation succeeds
pd.concat([fruits, vegetables])

               name  quantity
0             mango       NaN
1             guava       NaN
2            orange       NaN
0  Brussels sprouts       2.0
1           spinach       3.0
2          broccoli       4.0

In [10]:
# Axis=1 concatenates dataframes horizontally
# This is a column-wise concatenation
price_quality = pd.DataFrame({
    "price": [2.99, 1.99, 3.99],
    "presentation": ["frozen", "washed", "raw, bunch"] 
})

pd.concat([vegetables, price_quality], axis=1)

               name  quantity  price presentation
0  Brussels sprouts         2   2.99       frozen
1           spinach         3   1.99       washed
2          broccoli         4   3.99   raw, bunch

In [11]:
# concat can combine an arbitrary number of dataframes
# This can be helpful if you have lots of different data frames from multiple sources
pd.concat([vegetables, vegetables, vegetables, vegetables])

               name  quantity
0  Brussels sprouts         2
1           spinach         3
2          broccoli         4
0  Brussels sprouts         2
1           spinach         3
2          broccoli         4
0  Brussels sprouts         2
1           spinach         3
2          broccoli         4
0  Brussels sprouts         2
1           spinach         3
2          broccoli         4

## Using `.merge` to combine dataframes on common column values
- Database style join for Pandas Dataframes
- Pandas `.join` joins dataframes on identical column names that exist on both dataframes
- Using `.merge` can be more flexible, since sometimes the column names are not identical

## Types of Joins
- "Inner" returns records that have matching values in both tables.
- "Left" returns all records from the left table, and the matched records from the right table.
- "Right" returns all records from the right table, and the matched records from the left table.
- "Outer" Returns all records when there is a match in either left or right table.
| Join type | Rows kept |
| --- | --- |
| Inner | Rows with matching keys in both DataFrames |
| Left | Every left row and matching right rows |
| Right | Every right row and matching left rows |
| Outer | All rows from either DataFrame, matched where possible |

In [12]:
# Notice how role_id points to the id on the roles dataframe
# Take note of the missing data
users = pd.DataFrame({
    'user_id': [1, 2, 3, 4, 5, 6],
    'name': ['bob', 'mary', 'sally', 'adam', 'jane', 'mike'],
    'role_id': [1, 2, 3, 3, None, None]
})

users

   user_id   name  role_id
0        1    bob      1.0
1        2   mary      2.0
2        3  sally      3.0
3        4   adam      3.0
4        5   jane      NaN
5        6   mike      NaN

In [13]:
# Notice that the role id column is called "id" on the roles dataframe
roles = pd.DataFrame({
    'role_id': [1, 2, 3, 4],
    'role': ['admin', 'author', 'reviewer', 'commenter']
})

roles

   role_id       role
0        1      admin
1        2     author
2        3   reviewer
3        4  commenter

In [14]:
# An inner join returns members that exist on both the dataframes
users.merge(roles, left_on='role_id', right_on='role_id', how='inner')

   user_id   name  role_id      role
0        1    bob      1.0     admin
1        2   mary      2.0    author
2        3  sally      3.0  reviewer
3        4   adam      3.0  reviewer

In [15]:
# If the same exact column name exists on both dataframes, we can use the "on" argument
users.merge(roles, on='role_id', how='inner')

   user_id   name  role_id      role
0        1    bob      1.0     admin
1        2   mary      2.0    author
2        3  sally      3.0  reviewer
3        4   adam      3.0  reviewer

In [16]:
# Notice that the left join keeps all records from the users dataframe, even if they are missing on the right dataframe
users.merge(roles, on='role_id', how='left')

   user_id   name  role_id      role
0        1    bob      1.0     admin
1        2   mary      2.0    author
2        3  sally      3.0  reviewer
3        4   adam      3.0  reviewer
4        5   jane      NaN       NaN
5        6   mike      NaN       NaN

In [17]:
# Notice that the right join keeps all records from the users dataframe, even if they are missing on the right dataframe
users.merge(roles, left_on='role_id', right_on='role_id', how='right')

   user_id   name  role_id       role
0      1.0    bob      1.0      admin
1      2.0   mary      2.0     author
2      3.0  sally      3.0   reviewer
3      4.0   adam      3.0   reviewer
4      NaN    NaN      4.0  commenter

In [18]:
# The outer join keeps all records from every dataframe, but values are associated, where applicable
# Outer joins keep all values including nulls
users.merge(roles, on='role_id', how='outer')

   user_id   name  role_id       role
0      1.0    bob      1.0      admin
1      2.0   mary      2.0     author
2      3.0  sally      3.0   reviewer
3      4.0   adam      3.0   reviewer
4      NaN    NaN      4.0  commenter
5      5.0   jane      NaN        NaN
6      6.0   mike      NaN        NaN

In [19]:
# Relationship between dataframe order and join type 
# Consider the result of starting with users and left joining roles
users.merge(roles, on="role_id", how='left')

   user_id   name  role_id      role
0        1    bob      1.0     admin
1        2   mary      2.0    author
2        3  sally      3.0  reviewer
3        4   adam      3.0  reviewer
4        5   jane      NaN       NaN
5        6   mike      NaN       NaN

In [20]:
# Compare to starting with roles and using right join with users
roles.merge(users, on="role_id", how='right')

   role_id      role  user_id   name
0      1.0     admin        1    bob
1      2.0    author        2   mary
2      3.0  reviewer        3  sally
3      3.0  reviewer        4   adam
4      NaN       NaN        5   jane
5      NaN       NaN        6   mike

## Additional Resources
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html
- https://pandas.pydata.org/docs/user_guide/merging.html
- https://pandas.pydata.org/pandas-docs/stable/getting_started/comparison/comparison_with_sql.html#compare-with-sql-join

## Exercises
- Read "2020_sales.csv", "2021_sales.csv", and "2022_sales.csv" into dataframes, then concatenate these 3 dataframes vertically.
- Create a `posts` dataframe of the following information. 
```
[
    {
        "author_id": 1,
        "title": "How I Learned Python"
    },
    {
        "author_id": 2,
        "title": "How I Learned to Stop Worrying and Love Pandas"
    },
    {
        "author_id": 2,
        "title": "Quick Tutorial on Installing Anaconda"
    },
    {
        "author_id": 9,
        "title": "Learning Pandas If You Already Work With Spreadsheets"
    }
]
```
- Perform an inner join of `users` and `posts`. *Hint* Think about what data these two dataframes share in common.
- Start with `users` then left join the `posts` dataframe.
- Start with `users` then right join the `posts` dataframe.
- Finally, perform an outer join of `users` and `posts`.

In [21]:
# Read "2020_sales.csv", "2021_sales.csv", and `"2022_sales.csv" into dataframes
# Concatenate these 3 dataframes together, vertically


sales_2020 = pd.read_csv(DATA_DIR / "2020_sales.csv")
sales_2021 = pd.read_csv(DATA_DIR / "2021_sales.csv")
sales_2022 = pd.read_csv(DATA_DIR / "2022_sales.csv")
sales = pd.concat([sales_2020, sales_2021, sales_2022], ignore_index=True)
sales

   year             items  units
0  2020            trucks     20
1  2020            sedans     15
2  2020  compact vehicles     14
3  2021            trucks     35
4  2021            sedans     30
5  2021  compact vehicles     17
6  2022            trucks     40
7  2022            sedans     31
8  2022  compact vehicles     35

In [22]:
# Create a `posts` dataframe of the above blog post data


posts = pd.DataFrame([
    {"author_id": 1, "title": "How I Learned Python"},
    {"author_id": 2, "title": "How I Learned to Stop Worrying and Love Pandas"},
    {"author_id": 2, "title": "Quick Tutorial on Installing Anaconda"},
    {"author_id": 9, "title": "Learning Pandas If You Already Work With Spreadsheets"},
])
posts

   author_id                                              title
0          1                               How I Learned Python
1          2     How I Learned to Stop Worrying and Love Pandas
2          2              Quick Tutorial on Installing Anaconda
3          9  Learning Pandas If You Already Work With Sprea...

In [23]:
users

   user_id   name  role_id
0        1    bob      1.0
1        2   mary      2.0
2        3  sally      3.0
3        4   adam      3.0
4        5   jane      NaN
5        6   mike      NaN

In [24]:
# Perform an inner join of `users` and `posts`. 
# Hint: Think about what data these two dataframes share in common.


users.merge(posts, left_on="user_id", right_on="author_id", how="inner")

,user_id,name,role_id,author_id,title
0,1,bob,1.0,1,How I Learned Python
1,2,mary,2.0,2,How I Learned to Stop Worrying and Love Pandas
2,2,mary,2.0,2,Quick Tutorial on Installing Anaconda

In [25]:
# Start with `users` then left join the `posts` dataframe


users.merge(posts, left_on="user_id", right_on="author_id", how="left")

,user_id,name,role_id,author_id,title
0,1,bob,1.0,1.0,How I Learned Python
1,2,mary,2.0,2.0,How I Learned to Stop Worrying and Love Pandas
2,2,mary,2.0,2.0,Quick Tutorial on Installing Anaconda
3,3,sally,3.0,NaN,NaN
4,4,adam,3.0,NaN,NaN
5,5,jane,NaN,NaN,NaN
6,6,mike,NaN,NaN,NaN

In [26]:
# Start with `users` then right join the `posts` dataframe


users.merge(posts, left_on="user_id", right_on="author_id", how="right")

,user_id,name,role_id,author_id,title
0,1.0,bob,1.0,1,How I Learned Python
1,2.0,mary,2.0,2,How I Learned to Stop Worrying and Love Pandas
2,2.0,mary,2.0,2,Quick Tutorial on Installing Anaconda
3,NaN,NaN,NaN,9,Learning Pandas If You Already Work With Sprea...

In [27]:
# Finally, perform an outer join of `users` and `posts`


users.merge(posts, left_on="user_id", right_on="author_id", how="outer")

,user_id,name,role_id,author_id,title
0,1.0,bob,1.0,1.0,How I Learned Python
1,2.0,mary,2.0,2.0,How I Learned to Stop Worrying and Love Pandas
2,2.0,mary,2.0,2.0,Quick Tutorial on Installing Anaconda
3,3.0,sally,3.0,NaN,NaN
4,4.0,adam,3.0,NaN,NaN
5,5.0,jane,NaN,NaN,NaN
6,6.0,mike,NaN,NaN,NaN
7,NaN,NaN,NaN,9.0,Learning Pandas If You Already Work With Sprea...

---

## Course lesson: 05_Advanced_Dataframes_02.ipynb

# Intro to Pandas
by Ryan Orsinger

## Module 5: Working With Files
- More on using `pd.read_csv`
    - HTTP Requests
    - Working with files that use delimiters/separators other than commas
    - Setting the index column
- Writing data with `to_csv`
- Reading JSON
- Reading from Excel files
- Writing to Excel files

In [28]:
import pandas as pd

In [29]:
# read_csv can read from hosted CSV files.
# Pandas sends the http request!
url = "https://gist.githubusercontent.com/ryanorsinger/cc276eea59e8295204d1f581c8da509f/raw/2388559aef7a0700eb31e7604351364b16e99653/mall_customers.csv"
pd.read_csv(url).head()

   customer_id  gender  age  annual_income  spending_score
0            1    Male   19             15              39
1            2    Male   21             15              81
2            3  Female   20             16               6
3            4  Female   23             16              77
4            5  Female   31             17              40

In [30]:
# To set the index column, use the index_col argument
# If you notice a column that makes sense to use as the index, you'll need to specic
pd.read_csv(url, index_col="customer_id").head()

             gender  age  annual_income  spending_score
customer_id
1              Male   19             15              39
2              Male   21             15              81
3            Female   20             16               6
4            Female   23             16              77
5            Female   31             17              40

In [31]:
# The ! operator inside of Jupyter Notebooks or iPython issues a command to the terminal
# If you use Windows without the Linux Subsystem enabled, use !dir *.csv
!ls *.csv

sorted(str(path) for path in DATA_DIR.glob("*.csv"))

'ls' is not recognized as an internal or external command,
operable program or batch file.

['Datasets\\2020_sales.csv',
 'Datasets\\2021_sales.csv',
 'Datasets\\2022_sales.csv',
 'Datasets\\mpg.csv']

In [32]:
!ls *sales*.csv

sorted(str(path) for path in DATA_DIR.glob("*sales*.csv"))

'ls' is not recognized as an internal or external command,
operable program or batch file.

['Datasets\\2020_sales.csv',
 'Datasets\\2021_sales.csv',
 'Datasets\\2022_sales.csv']

In [33]:
sales_files = !ls *sales*.csv
sales_files

sales_files = sorted(DATA_DIR.glob("*sales*.csv"))
sales_files

[WindowsPath('Datasets/2020_sales.csv'),
 WindowsPath('Datasets/2021_sales.csv'),
 WindowsPath('Datasets/2022_sales.csv')]

In [34]:
# Programmatically Reading Multiple Files 
sales_data = []
for file in sales_files:
    df = pd.read_csv(file)
    sales_data.append(df)
    
sales_df = pd.concat(sales_data, ignore_index=True)
sales_df

sales_data = []
for file in sales_files:
    df = pd.read_csv(file)
    sales_data.append(df)

sales_df = pd.concat(sales_data, ignore_index=True)
sales_df

   year             items  units
0  2020            trucks     20
1  2020            sedans     15
2  2020  compact vehicles     14
3  2021            trucks     35
4  2021            sedans     30
5  2021  compact vehicles     17
6  2022            trucks     40
7  2022            sedans     31
8  2022  compact vehicles     35

In [35]:
# It's common in the field to combine many different data sources into a single dataframe for cleaning/analysis
# Writing to_csv will write the index values to their own column on the data
sales_df.to_csv("all_sales.csv")

sales_df.to_csv("all_sales.csv", index=False)

In [36]:
!ls *.csv

sorted(path.name for path in Path(".").glob("*.csv"))

'ls' is not recognized as an internal or external command,
operable program or batch file.

['all_sales.csv', 'all_sales_clean.csv', 'quotes.csv']

In [37]:
# Notice how the left-over column is turned into an unnamed column
pd.read_csv("all_sales.csv").head()

pd.read_csv("all_sales.csv").head()

   year             items  units
0  2020            trucks     20
1  2020            sedans     15
2  2020  compact vehicles     14
3  2021            trucks     35
4  2021            sedans     30

In [38]:
# Let's see an example where we avoid this complication by paying more attention to the index
# The index argument on to_csv takes a boolean and defaults to True
sales_df.to_csv("all_sales_clean.csv", index=False)

sales_df.to_csv("all_sales_clean.csv", index=False)

In [39]:
# Notice that the index is regenerated and is appropriate
pd.read_csv("all_sales_clean.csv")

pd.read_csv("all_sales_clean.csv")

   year             items  units
0  2020            trucks     20
1  2020            sedans     15
2  2020  compact vehicles     14
3  2021            trucks     35
4  2021            sedans     30
5  2021  compact vehicles     17
6  2022            trucks     40
7  2022            sedans     31
8  2022  compact vehicles     35

If you use a named index column instead of only the autogenerated index, you will avoid this.

### Note on Separator Characters, called Delimiters
- CSV files use commas to separate values
- You may encounter files that use another delimiter character than a comma
- Tab separated files are common in logfiles and spreadsheet exports
- Sometimes, you may encounter a file extension of .tsv for tab-separated-values
- You may encounter delimiters other than commas or tabs in plain text files.
- Use `pd.read_csv` for them (unless the file is .JSON), and identify the appropriate character

In [40]:
# The "\t" character is how we specify a tab character
pd.read_csv(DATA_DIR / "penguins_with_tabs.tsv", sep="\t").head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [41]:
# The course example API is no longer available (HTTP 410). Use the stable JSON source from the exercise.
dolly_url = "https://gist.githubusercontent.com/ryanorsinger/ad042d8ee4340ae7026e215bc6b69665/raw/4c0eef2e4cbce5e47b674e8d1d5bad34f0c7b757/dolly.json"
curie_quotes = pd.read_json(dolly_url)
curie_quotes.head()

                                               quote        author
0  We cannot direct the wind, but we can adjust t...  Dolly Parton
1          Find out who you are and do it on purpose  Dolly Parton
2  If you don't like the road you're walking, sta...  Dolly Parton
3  You'll never do a whole lot unless you're brav...  Dolly Parton
4  I'm not going to limit myself just because peo...  Dolly Parton

## Example of using `read_clipboard`

|     model |             displ | year |  cyl | trans |        drv |  cty |  hwy |   fl | drv   | class   |
| --------: | ----------------: | ---: | ---: | ----: | ---------: | ---: | ---: | ---: | ----: | ------- |
|      audi |                a4 |  2.0 | 2008 |     4 |   auto(av) |    f |   21 |   30 |     p | compact |
|     dodge | dakota pickup 4wd |  3.9 | 1999 |     6 | manual(m5) |    4 |   14 |   17 |     r | pickup  |
|    toyota |       4runner 4wd |  4.7 | 2008 |     8 |   auto(l5) |    4 |   14 |   17 |     r | suv     |
|     dodge |       caravan 2wd |  3.8 | 2008 |     6 |   auto(l6) |    f |   16 |   23 |     r | minivan |
| chevrolet |            malibu |  3.6 | 2008 |     6 |   auto(s6) |    f |   17 |   26 |     r | midsize |

In [42]:
# Clipboard access requires an interactive copied table. Use the provided mpg.csv for a reproducible example.
df = pd.read_csv(DATA_DIR / "mpg.csv")
df.head()

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [43]:
# Writing a dataframe in memory to an excel file
df.to_excel("mpg.xlsx", index=None)

df.to_excel("mpg.xlsx", index=False)

In [44]:
# Reading an excel file (simple version)
mpg = pd.read_excel("mpg.xlsx")

mpg_from_excel = pd.read_excel("mpg.xlsx")
mpg_from_excel.head()

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [45]:
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [46]:
# Reading a specific sheet from an excel file
pd.read_excel(DATA_DIR / "example_spreadsheet.xlsx", sheet_name="grocery_list")

pd.read_excel(DATA_DIR / "example_spreadsheet.xlsx", sheet_name="grocery_list")

           item  price  quantity
0      cat foot   3.99         2
1  toilet paper   7.99         1
2         beans   0.99         2
3          corn   0.75         4

In [47]:
# Notice how there's some extra
pd.read_excel(DATA_DIR / "example_spreadsheet.xlsx", sheet_name="pet_info")

pd.read_excel(DATA_DIR / "example_spreadsheet.xlsx", sheet_name="pet_info")

                           Fancy Company Reports Unnamed: 1 Unnamed: 2
0         Quality service for all your pet needs        NaN        NaN
1  Company Motto: when your companion is in need        NaN        NaN
2                                            NaN        NaN        NaN
3                                       Pet Name    Species     weight
4                                         Fluffy        cat          8
5                                            Max        dog         18
6                                            Gus     iguana         12

In [48]:
# Sometimes, you may need to open the spreadsheet to identify the columns to skip
pd.read_excel(DATA_DIR / "example_spreadsheet.xlsx", sheet_name="pet_info", skiprows=4)

pd.read_excel(DATA_DIR / "example_spreadsheet.xlsx", sheet_name="pet_info", skiprows=4)

  Pet Name Species  weight
0   Fluffy     cat       8
1      Max     dog      18
2      Gus  iguana      12

## Additional Resources
- https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
- https://pandas.pydata.org/docs/reference/api/pandas.read_clipboard.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_clipboard.html
- https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html
- Other formats https://pandas.pydata.org/docs/user_guide/io.html
    - SQL
    - XML
    - STATA
    - SAS
    - SPSS

## Exercise 2: Working with JSON, CSV, and Excel files

The following tasks read the specified quote and drink datasets, combine records or columns as requested, and save the results as `quotes.csv` and `drinks.xlsx`.

### Read Dolly Parton and Bob Ross quotes; add a quote; concatenate and save

In [49]:
dolly_url = "https://gist.githubusercontent.com/ryanorsinger/ad042d8ee4340ae7026e215bc6b69665/raw/4c0eef2e4cbce5e47b674e8d1d5bad34f0c7b757/dolly.json"
dolly = pd.read_json(dolly_url)
dolly.head()

                                               quote        author
0  We cannot direct the wind, but we can adjust t...  Dolly Parton
1          Find out who you are and do it on purpose  Dolly Parton
2  If you don't like the road you're walking, sta...  Dolly Parton
3  You'll never do a whole lot unless you're brav...  Dolly Parton
4  I'm not going to limit myself just because peo...  Dolly Parton

In [50]:
bob_url = "https://gist.githubusercontent.com/ryanorsinger/ad042d8ee4340ae7026e215bc6b69665/raw/b0c1c816d87e4d3db34e52d35e376394f689911e/bob_ross.json"
bob = pd.read_json(bob_url)
bob.head()

                                               quote    author
0  We don't make mistakes, just happy little acci...  Bob Ross
1  Talent is a pursued interest. In other words, ...  Bob Ross
2  Anything that you try and you don't succeed, i...  Bob Ross

In [51]:
my_quote = pd.DataFrame([
    {"quote": "The secret of getting ahead is getting started.", "author": "Mark Twain"}
])
my_quote

                                             quote      author
0  The secret of getting ahead is getting started.  Mark Twain

In [52]:
quotes = pd.concat([dolly, bob, my_quote], ignore_index=True)
quotes

                                               quote        author
0  We cannot direct the wind, but we can adjust t...  Dolly Parton
1          Find out who you are and do it on purpose  Dolly Parton
2  If you don't like the road you're walking, sta...  Dolly Parton
3  You'll never do a whole lot unless you're brav...  Dolly Parton
4  I'm not going to limit myself just because peo...  Dolly Parton
5  I think everybody has the right to be who they...  Dolly Parton
6  We don't make mistakes, just happy little acci...      Bob Ross
7  Talent is a pursued interest. In other words, ...      Bob Ross
8  Anything that you try and you don't succeed, i...      Bob Ross
9    The secret of getting ahead is getting started.    Mark Twain

In [53]:
quotes.to_csv("quotes.csv", index=False)
pd.read_csv("quotes.csv").tail()

                                               quote        author
5  I think everybody has the right to be who they...  Dolly Parton
6  We don't make mistakes, just happy little acci...      Bob Ross
7  Talent is a pursued interest. In other words, ...      Bob Ross
8  Anything that you try and you don't succeed, i...      Bob Ross
9    The secret of getting ahead is getting started.    Mark Twain

### Read drink data and costs; concatenate columns; save to Excel

In [54]:
drinks_url = "https://gist.githubusercontent.com/ryanorsinger/ad042d8ee4340ae7026e215bc6b69665/raw/b0c1c816d87e4d3db34e52d35e376394f689911e/drinks.json"
drinks = pd.read_json(drinks_url)
drinks

           type  calories  number_consumed  caffeinated
0         water         0                7            0
1  orange juice       220                4            0
2      gatorade       140                1            0
3    cappuccino       350                2            1
4       hot tea         5                3            1

In [55]:
drink_cost_url = "https://gist.githubusercontent.com/ryanorsinger/ad042d8ee4340ae7026e215bc6b69665/raw/b0c1c816d87e4d3db34e52d35e376394f689911e/drink_cost.csv"
drink_costs = pd.read_csv(drink_cost_url)
drink_costs

   price   tax
0   0.00  0.00
1   2.99  0.06
2   1.99  0.07
3   3.99  0.07
4   0.99  0.07

In [56]:
drinks = pd.concat([drinks, drink_costs], axis=1)
drinks

           type  calories  number_consumed  caffeinated  price   tax
0         water         0                7            0   0.00  0.00
1  orange juice       220                4            0   2.99  0.06
2      gatorade       140                1            0   1.99  0.07
3    cappuccino       350                2            1   3.99  0.07
4       hot tea         5                3            1   0.99  0.07

In [57]:
drinks.to_excel("drinks.xlsx", index=False)
pd.read_excel("drinks.xlsx").head()

           type  calories  number_consumed  caffeinated  price   tax
0         water         0                7            0   0.00  0.00
1  orange juice       220                4            0   2.99  0.06
2      gatorade       140                1            0   1.99  0.07
3    cappuccino       350                2            1   3.99  0.07
4       hot tea         5                3            1   0.99  0.07